src/routes/Domestic.jsx
=> Fix: fix routes domestic link error

src/components/BuzzChart/index.jsx, src/components/EmotionChart/index.jsx, src/components/PressChart/index.jsx
차트의 tickValue를 적절한 값으로 (정수 등) 설정하였습니다.
=> #37 Fix: set chart tickvalue

src/routes/DomesticFinance/index.jsx
remove margin in domesticfinance page
=> Design: modify domesticfinance layout

src/reducers/domesticFinance/domesticFinance.js, src/routes/DomesticFinance/index.jsx, src/utils/getPreviousDate.js
utils 폴더에 getPreviousDate 함수를 더하였습니다.
getPreviousDate(date,numOfDays)
date는 date 객체이고 numOfDays는 몇일 전인지 정수값입니다.
date기준 numOfDays 전일의 날짜를 반환합니다.
=> add getPreviousDate function

src/components/CategoryChart/index.jsx, src/components/KeywordChart/index.jsx
CategoryChart의 렌더링 에러를 해결하였습니다.
단어데이터를 text에 직접 바인딩하였습니다.
=> Fix  CategoryChart rerender error

src/components/CorrelationChart/index.jsx, src/components/CorrelationChart/style.js, src/components/Search/index.jsx, src/components/Search/style.js
- 통계페이지 correlation 옵션 및 그래프 UI 생성
=> feat: Make correlation option and graph UI 

src/components/FinanceChart/index.jsx, src/components/FinanceChart/style.js
=> Feat: add financechart

src/components/Main/FinanceNews/index.jsx
=> Fix: finance news tab error

src/components/Main/RecentStock/style.js, src/components/Main/StockIndex/index.jsx, src/components/Main/StockIndex/style.js, src/routes/Domestic/Domestic.jsx, src/routes/Domestic/style.js, src/routes/Global/style.js, src/utils/useResponsive.js
1. useResponsive.js 추가
2. domestic main 반응형 로더 추가
=> Feat: make useResponsive util

package-lock.json, src/App.js, src/Router.js, src/components/Layout/RecentStock/index.js, src/components/Layout/Search/index.js
히스토리 순서 표시 변경
히스토리 아이템의 rate에 따라 색 표시 변경
확인을 위한 더미데이터 랜덤하게 할당
=> Feat: update search history components

src/components/Main/ExchangeRate/ExchangeRateChart/index.jsx, src/components/Main/ExchangeRate/index.jsx, src/components/Main/ExchangeRate/style.js
=> Refactor: update exchange rate chart lange and add animation

src/components/Main/ExchangeRate/ExchangeRateChart/index.jsx
=> Fix: modify label render logic

package-lock.json, package.json, public/images/resent_slide_arrow_next.svg, public/images/resent_slide_arrow_prev.svg, src/GlobalStyle.js, src/components/Main/ExchangeRate/style.js, src/components/Main/RecentStock/index.js, src/components/Main/RecentStock/style.js, src/components/Main/TopStock/index.jsx, src/components/Main/TopStock/style.js, src/routes/Domestic/Domestic.jsx, src/routes/Global/Global.jsx
=> Feat: add global main box animation

src/components/Main/TopStock/index.jsx
=> Feat: add top stock component sort function

src/components/Layout/Search/SearchBar.js, src/components/Layout/Search/SearchResult.js, src/components/Layout/Search/index.js, src/components/Layout/Search/style.js, src/components/Layout/StockInfo/index.js, src/routes/Home.jsx, src/utils/animatedCountUp.js
검색어를 입력하고 엔터를 누르거나 검색 아이콘을 누르면 첫번째 검색 결과로 이동
주식 개요 해외 정보(더미데이터) 연동
최근 조회로 보내는 props 이름 수정
=> Feat: move to first search result when press enter

src/components/Main/ExchangeRate/index.jsx, src/components/Main/RecentStock/style.js
=> Refactor: resent stock position, exchange rate value

src/components/StatisticsBarPathGraph/index.jsx, src/components/StatisticsPathGraph/index.jsx
=> Refactor: update statistics chart date

src/components/Layout/style.js, src/components/Search/index.jsx
x-ticker 검색시 location search로 쿼리 전달
=> Feat: Pass location query when searching x-tickerDevelop

src/components/ComInfoGraph/index.jsx, src/components/ComInfoGraph/style.js, src/components/ComInfoTable/index.jsx, src/components/DailyPrice/index.jsx, src/components/DailyPrice/style.js, src/components/Table/BetaTable/index.jsx, src/components/Table/BetaTable/style.js, src/components/Table/CorrelationTable/index.jsx, src/components/Table/StatisticsHeader/index.jsx, src/components/Table/StatisticsHeader/style.js, src/components/Table/TableHeader/index.jsx, src/routes/DoBeta/index.jsx, src/routes/DoComInfo/index.jsx, src/routes/DoCorrelation/index.jsx
=> Feat: add animation regression, correlation

src/Router.js, src/components/Layout/Nav/index.js, src/components/Layout/Nav/style.js
=> Feat: update nav style and responsive

src/routes/Global/Global.jsx
=> Refactor: change animation time

src/components/Layout/Search/index.js
엔터 / 검색 아이콘 클릭으로 종목 변경시에도 beta와 correlation 디폴트값 유지하도록 세팅
(국내 : 삼성 / 해외 : aapl)
=> Feat: set x-ticker default value when search submit event
